### ISSUE TITLE
Feature / Change Requests für V0.0.1

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.pid#18]
- [x] all Parameters (P, I, D, MIN, MAX) should be controllable using states.
- [x] reset should reset I store (sumErr) only
- [x] sumErr and diffErr should not be compted if I/D Term is disabled. null should be returnd in this case.

**Comment by BenAhrdt** [comment]
Also ich würde.
1. Zusätzlich zu der Generellen Begrenzung noch den I-Anteil begrenzen. (dass der nicht wegläuft).
2. Den I-Anteil resetbar machen (nicht nur den ganzen Regler)
3. Die Werte auf wirklich auf die PID Werte einstellbar machen ... nicht nur 1,2,3 (ohne erkennbare Einheit)
    Also: anstatt P => Kp ; anstatt I = Ki = 1/Tn => Tn einstellbar in s   bsp. 2s ergibt ein Ki von 1/2s = 0,5
    ansatt P => Kp = Tv => Ts einstellbas in s
    ..... ALSO
    Kp = 0.0 .... x.x
    Ki = 1/Tn mit Tn = 0.0 .... x.x
   Kp = Tv mit Tv = 0. ... x.x

Der I Anteil läuft hoch, obwohl er auf 0 gestellt ist:
![image](https://user-images.githubusercontent.com/92173565/228598616-6aefa905-6a63-4d5d-b0dd-0237db1fd802.png)

**Comment by mcm1957** [comment]
```1. Zusätzlich zu der Generellen Begrenzung noch den I-Anteil begrenzen. (dass der nicht wegläuft).```
Das sollte so umgesetzt sein. Allerdings ist lt. deinem Screenshot Min / Max nihct aktiviert (=null). Daher gibts auch keine Begrenzung. Ob du das nicht eingestellt hast oder es nicht funktioniert kann ich auf Grund des Screenshots nicht sagen.

```2. Den I-Anteil resetbar machen (nicht nur den ganzen Regler)```
OK. Da eigentlich nur der I Anteil ein hiostorisches Wissen hat, scheint es Sinn zu machen bei Reset nur deisen Speicher zu resetten.

```3. Die Werte auf wirklich auf die PID Werte einstellbar machen ... nicht nur 1,2,3 (ohne erkennbare Einheit)
    Also: anstatt P => Kp ; anstatt I = Ki = 1/Tn => Tn einstellbar in s   bsp. 2s ergibt ein Ki von 1/2s = 0,5
    ansatt P => Kp = Tv => Ts einstellbas in s
    ..... ALSO
    Kp = -x.x .... x.x
    Ki = 1/Tn mit Tn = -x.x .... x.x
   Kp = Tv mit Tv = -x.x ... x.x
(Wichtig !!! auch negative Werte zulassen, da auch diese eingestellt können werden müssen
Negative Werte werden derzeit nicht beachtet. (Ich nehme an, y ist der Ausgang (die Stellgröße und der wird immer positiv)
```
So ganz versteh ich 1,2,3 nicht Du kannst beliebige Dezimalwefrte für P, I, D eingeben.
Ob die Reglerfunktion von P / I / D Antielbzw. Faktor auf Zeitwerte umgestellt werden soll wird im Forum besprochen. Im Prinzip sind beide Darstellungen möglich - siehe z.B. node-pid-controller wo auch P, I, D Werte angegeben werden.

```Der I Anteil läuft hoch, obwohl er auf 0 gestellt ist:```
OK Die Berechnung  und Ausgabe der sumErr und diffErr Werte sollte bei abgeschaltetem I / D Anteil deaktiviert werden.

```Die Min und Max Grenze Greift garade nicht```
Siehe oben. Entweder hast du in der Config Min/Max nicht aktiviert (dann kannst du auch keine Werte dafür eingeben) oder es funktioniert nicht. Muss ich mir noch ansehen.

DANKE für Feedback

**Comment by BenAhrdt** [comment]
Der Screenshot war wegen dem I Anteil.
Das Begrenzen habe ich danach angeschaltet und es stand auch auf True und trotzdem funktionierte es nicht.
Historisch kann ich sagen, dass es Vorteile hat, wenn es nur der I Anteil ist und nicht der gesamte Regler (weil dann Kurz der P Anteil 0 ist.
Die Einheiten sind bei modernen Reglern so angegeben, da auch Berechnungen so gut übernommen werden können.

**Comment by mcm1957** [comment]
> Das Begrenzen habe ich danach angeschaltet und es stand auch auf True und trotzdem funktionierte es nicht.

OK - BUG (oder besser not ok :-) 

> Historisch kann ich sagen, dass es Vorteile hat, wenn es nur der I Anteil ist und nicht der gesamte Regler (weil dann Kurz der P Anteil 0 ist.
OK - ist schon in der Taskliste

> Die Einheiten sind bei modernen Reglern so angegeben, da auch Berechnungen so gut übernommen werden können.
OK - ich wart noch auf klere Rückmeldungen im Forum, aber es sieht für mich so aus als wär ne Umstellung auf tn/tv gewunschen.

**Comment by mcm1957** [comment]
sollte ab 0.0.2-alpha.2 umgesetzt sein
