### ISSUE TITLE
[BUG] updates occure more often than cycle time specifies

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.pid#41]
die Regler zykluszeit änderungen haben bei mir keinen Einfluss.
Ich habe gerade die Zykluszeit einmal auf 10000ms gestellt.
Der Ist wert kommt natürlich trotzdem alle 2000ms rein (in meinem Fall jetzt).
der Regler aktualisiert sich dann im 2000ms zyklus.

0.0.2-alpha.2

**Comment by fu-zhou** [comment]
Ist eindeutig nachvollziehbar: Sobald run auf true gesetzt wird (über den state) wird die Zyklsuszeit ignoriert. Ist "automatischer Start" aktiviert, läuft der Regler im Zyklus. Dann run auf false und wieder auf true => Zyklus wird ignoriert. Bei deaktivierterm automatischem Start langt das Setzen von run auf true um den Regler im willkürlichen (sich ändernden) Zyklus zu starten.

**Comment by mcm1957** [comment]
fixed at 0.0.3-alpha.0
