### ISSUE TITLE
[BUG] Regler fängt nicht an, ohne auf den set zu schreiben

### ISSUE THREAD

**Issue by BenAhrdt** [iobroker-community-adapters/ioBroker.pid#43]
Ich starte den Regler neu und y wird erst geschrieben, wenn set einmal geschrieben wird.
![regler start](https://user-images.githubusercontent.com/92173565/230709710-54fb4a05-6d0d-4634-963b-4250fd541266.gif)

**Comment by mcm1957** [comment]
0.0.2-alpha.2

**Comment by mcm1957** [comment]
Reason: act and set have NOT been read from existing states, so controller started with 0 / 0.

**Comment by BenAhrdt** [comment]
Also ich habe es gerade noch mal getestet.
Das Verhalten ist noch wie vorher. (Keine Änderung - Immer geht die Regeleung erst, wenn set gesetzt wird.
Zwischendurch hatte ich den EIndruck es würde gehen, aber jetzt irgendwie immer nach nem Neustart nicht mehr.

**Comment by mcm1957** [comment]
Ich hab noch keine neue Release veröffentlicht.

**Comment by BenAhrdt** [comment]
Ich dachte das wäre entsprechend in der 0.0.2. alpha 2 drin. 🙈

**Comment by mcm1957** [comment]
fixed at 0.0.3-alpha.0
