### ISSUE TITLE
Übersetzungen

### ISSUE THREAD

**Issue by fu-zhou** [iobroker-community-adapters/ioBroker.pid#7]
I-Anteil wird als "ich schätze" angezeigt
"ermöglicht" sollte wohl eher "aktiviert" heißen

![image](https://user-images.githubusercontent.com/11984960/227361916-cdc84a70-0945-48dc-bc03-856dc27d33e7.png)

**Comment by mcm1957** [comment]
Das GUI ist noch ALPHA. 
Code ist noch nicht mal ALPHA !
Bitte derzeit maximal die englische Version des GUI ansehen - ich hab den Rest nicht mal gechecked.
Und da maximal checken ob wichtige Parameter zu fehlen scheinen oder sonstwie unsionnig sind.

**Comment by mcm1957** [comment]
Lets close here due to alpha state.

Please report further nonsense within new issues.
